import { defaultCategories } from './budget.js';
const escape = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = value => `${Number(value).toLocaleString('it-IT',{maximumFractionDigits:2})} €`;
export function budgetHomeContent(state, guide, balances) {
 const buckets=[['needs','Necessità',50,'needsSpent'],['wants','Svago',30,'wantsSpent'],['future','Risparmio',20,'futureCommitted']];
 const categories={...defaultCategories,...state.budgetCategories};
 if(!state.capitalConfigured)return `<section class="quota-home"><h1>Dividi il tuo capitale.</h1><p>Inserisci conto e contanti per creare le tue tre quote.</p><button class="button" data-capital>Inserisci il capitale</button><button class="text-button" data-budget-method>Cambia metodo</button></section>`;
 return `<div class="quota-home"><header class="quota-heading"><div><span class="eyebrow">${new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</span><h1>${state.name?`Buongiorno,<br>${escape(state.name)}.`:'Tre quote.<br>Il tuo equilibrio.'}</h1><span class="quota-hero-rule" aria-hidden="true"></span></div><aside class="quota-mantra">Un posto per oggi.<br>Uno per domani.</aside><span class="quota-hero-caption">Il tuo equilibrio · 50/30/20</span></header><div class="quota-paper">
 <section class="quota-capital" aria-label="Capitale e saldo"><div><span>Budget di partenza</span><strong>${money(guide.capital)}</strong></div><div><span>Disponibile oggi</span><b>${money(balances.account+balances.cash)}</b><button class="text-button" data-capital>Conto ${money(balances.account)} · Contanti ${money(balances.cash)}</button></div></section>
 <div class="quota-proportions" aria-label="Ripartizione: 50% necessità, 30% svago, 20% risparmio"><span>50%</span><span>30%</span><span>20%</span></div>
 <div class="quota-section-title"><h2>Quanto puoi ancora usare</h2><button class="text-button" data-budget-method>Assegna categorie</button></div>
 <section class="quota-list" aria-label="Le tue tre quote">${buckets.map(([key,label,percentage,spentKey])=>{
 const remaining=guide[key+'Remaining'],target=guide[key+'Target'],spent=guide[spentKey],ratio=target>0?Math.min(1,Math.max(0,spent/target)):spent>0?1:0;
 const names=Object.entries(categories).filter(([,bucket])=>bucket===key).map(([name])=>name);
 return `<article class="quota-row quota-${key} ${remaining<0?'quota-over':''}"><div class="quota-label"><span class="quota-percent">${percentage}<small>%</small></span><div><h3>${label}</h3><span>Spese e versamenti assegnati</span></div></div><div class="quota-remaining"><strong>${money(Math.max(0,remaining))}</strong><span>ancora disponibili</span></div><div class="quota-track" role="progressbar" aria-label="${label}: ${money(spent)} usati su ${money(target)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(ratio*100)}"><i style="--quota-used:${ratio}"></i></div><div class="quota-ledger"><span>${key==='future'?'Utilizzati':'Spesi'} <b>${money(spent)}</b></span><span>Budget <b>${money(target)}</b></span></div>${remaining<0?`<p class="quota-warning" role="status">Quota superata di ${money(-remaining)}. Le altre quote restano separate.</p>`:''}<details class="quota-categories"><summary>Categorie di questa quota <span>${names.length}</span></summary><p>${names.length?names.map(escape).join(' · '):'Nessuna categoria assegnata.'}</p><button class="text-button" data-budget-method>Modifica assegnazioni</button></details></article>`;
 }).join('')}</section>
 <div class="quota-actions"><button class="button" data-add>Registra una spesa</button><button class="text-button" data-view="transactions">Vedi movimenti</button></div>
 ${guide.unallocatedIncome>0?`<aside class="quota-income"><strong>${money(guide.unallocatedIncome)} di nuove entrate</strong><p>Sono nel saldo, ma non ancora nelle tre quote.</p><button class="text-button" data-budget-method>Gestisci la ripartizione</button></aside>`:''}
 <details class="quota-explanation"><summary>Come funzionano questi importi?</summary><p>Le percentuali si applicano al capitale iniziale della ripartizione. Le spese registrate, anche in Adattivo, riducono la quota della categoria assegnata. Le spese programmate vengono conteggiate alla loro data. Al primo avvio il budget di partenza include anche le uscite già registrate, per mostrarle senza sottrarle due volte dal saldo. Una nuova ripartizione esplicita avvia invece un nuovo periodo.</p><p>Puoi iniziare una nuova ripartizione dal menu “Cambia metodo”. I piani mensili restano consultabili nella sezione Piano.</p></details></div></div>`;
}
