import {cloudUser,loadCloudWallet} from '../cloud.js?v=40';
import {monthlyTimeline,money} from '../engine.js?v=28';

export function createAgenda({onClose,reduced}){
 const dialog=document.createElement('dialog');dialog.id='agenda';dialog.setAttribute('aria-label','La tua agenda');
 dialog.innerHTML=`<button class="agenda-dismiss" aria-label="Riponi l’agenda">Riponi ×</button><div class="agenda-stage"><div class="agenda-book"><div class="agenda-pages"><section class="agenda-left"><small>RIENTRO / PERSONALE</small><h2>Le cose<br>che contano.</h2><p class="agenda-owner"></p><div class="agenda-date"></div><span class="agenda-binding" aria-hidden="true"></span></section><section class="agenda-paper" aria-live="polite"><div class="agenda-content"></div><footer><button class="agenda-prev" aria-label="Pagina precedente">←</button><span class="agenda-number"></span><button class="agenda-next" aria-label="Pagina successiva">→</button></footer></section><div class="agenda-leaf" aria-hidden="true"></div></div><button class="agenda-cover" aria-label="Apri la copertina dell’agenda"><span>RIENTRO</span><strong>Appunti<br>di vita.</strong><i>IL TUO SPAZIO PERSONALE</i><b>Apri l’agenda ↗</b></button></div></div><p class="agenda-hint">Apri la copertina. Prenditi un momento.</p>`;
 document.body.append(dialog);
 const q=s=>dialog.querySelector(s);let page=0,wallet=null,session=0,turning=false,noteKey='',timer;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function render(){
  const user=cloudUser();if(!user)return close(true);
  q('.agenda-number').textContent=`0${page+1} / 03`;q('.agenda-prev').disabled=page===0;q('.agenda-next').disabled=page===2;
  if(page===0)q('.agenda-content').innerHTML=`<small>01 / IL PROPRIETARIO</small><h3>Questa agenda<br>appartiene a</h3><p class="agenda-signature">${esc(wallet?.name||'Te.')}</p><p class="agenda-caption">${esc(user.email||'')}</p><div class="agenda-stamp">PERSONALE<br>DA CONSERVARE</div><p class="agenda-bottom">Un po’ di ordine.<br>Un po’ di spazio per te.</p>`;
  if(page===1){const events=wallet?monthlyTimeline(wallet):[];q('.agenda-content').innerHTML=`<small>02 / ${esc(new Date().toLocaleDateString('it-IT',{month:'long',year:'numeric'}))}</small><h3>Da ricordare.</h3><div class="agenda-events">${events.length?events.map(e=>`<div class="agenda-event"><b>${String(e.day).padStart(2,'0')}</b><span>${esc(e.label)}<small>${e.status==='done'?'Registrato':e.status==='overdue'?'Da verificare':'In programma'}</small></span><em>${esc(money(e.amount))}</em></div>`).join(''):'<p>Nessuna scadenza annotata per questo mese.</p>'}</div>`;}
  if(page===2){q('.agenda-content').innerHTML='<small>03 / PENSIERI IN LIBERTÀ</small><h3>Una cosa alla volta.</h3><label class="agenda-note-label" for="agenda-note">Le tue note personali</label><textarea id="agenda-note" maxlength="6000" placeholder="Quello che vuoi ricordarti…"></textarea><p class="agenda-note-status" role="status">Le note restano su questo dispositivo.</p>';try{q('textarea').value=localStorage.getItem(noteKey)||'';}catch{}q('textarea').oninput=()=>{try{localStorage.setItem(noteKey,q('textarea').value);q('.agenda-note-status').textContent='Annotato · solo su questo dispositivo';}catch{q('.agenda-note-status').textContent='Impossibile salvare qui. Copia le note prima di chiudere.';}};}
 }
 async function turn(direction){if(turning||page+direction<0||page+direction>2)return;turning=true;dialog.dataset.direction=direction>0?'next':'prev';dialog.classList.add('turning');const run=session;await new Promise(r=>setTimeout(r,reduced()?0:340));if(run!==session)return;page+=direction;render();await new Promise(r=>setTimeout(r,reduced()?0:360));if(run!==session)return;dialog.classList.remove('turning');turning=false;}
 q('.agenda-prev').onclick=()=>turn(-1);q('.agenda-next').onclick=()=>turn(1);
 q('.agenda-cover').onclick=()=>{dialog.classList.add('book-open');q('.agenda-pages').inert=false;q('.agenda-cover').inert=true;q('.agenda-hint').textContent='Sfoglia con le frecce. La tua agenda, pagina dopo pagina.';q('.agenda-next').focus({preventScroll:true});};
 function close(immediate=false){++session;clearTimeout(timer);dialog.classList.remove('book-open','turning');turning=false;q('.agenda-cover').inert=false;q('.agenda-pages').inert=true;const finish=()=>{dialog.close();wallet=null;q('.agenda-content').replaceChildren();q('.agenda-owner').textContent='';if(!immediate)onClose();};if(immediate||reduced())finish();else timer=setTimeout(finish,650);}
 q('.agenda-dismiss').onclick=()=>close();dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.addEventListener('keydown',e=>{if(e.target.tagName==='TEXTAREA')return;if(e.key==='ArrowRight'&&dialog.classList.contains('book-open')){e.preventDefault();turn(1);}if(e.key==='ArrowLeft'&&dialog.classList.contains('book-open')){e.preventDefault();turn(-1);}});
 return {close,async open(){const user=cloudUser();if(!user)return;const run=++session;page=0;turning=false;dialog.classList.remove('book-open','turning');dialog.classList.toggle('still',reduced());q('.agenda-cover').inert=false;q('.agenda-pages').inert=true;q('.agenda-hint').textContent='Apri la copertina. Prenditi un momento.';q('.agenda-cover').disabled=true;q('.agenda-cover b').textContent='Preparo le pagine…';q('.agenda-date').textContent=new Date().toLocaleDateString('it-IT',{day:'numeric',month:'long',year:'numeric'});dialog.showModal();try{wallet=await loadCloudWallet();if(run!==session||cloudUser()?.id!==user.id)return;noteKey=`rientro-agenda-notes:${user.id||user.email}`;q('.agenda-owner').textContent=wallet?.name||'La tua agenda';render();q('.agenda-cover').disabled=false;q('.agenda-cover b').textContent='Apri l’agenda ↗';q('.agenda-cover').focus();}catch{if(run!==session)return;q('.agenda-hint').textContent='Non riesco a caricare i tuoi dati. Riponi l’agenda e riprova.';q('.agenda-cover b').textContent='Connessione non disponibile';}}};
}
