import * as T from './vendor/three.module.js';
import {RoundedBoxGeometry} from './vendor/RoundedBoxGeometry.js';
import {GLTFLoader} from './vendor/addons/loaders/GLTFLoader.js';
import {EffectComposer} from './vendor/addons/postprocessing/EffectComposer.js';
import {SSAOPass} from './vendor/addons/postprocessing/SSAOPass.js';
import {OutputPass} from './vendor/addons/postprocessing/OutputPass.js';
import {RenderPass} from './vendor/addons/postprocessing/RenderPass.js';
import {RoomEnvironment} from './vendor/RoomEnvironment.js';
import {pagePoint,smoothCamera,dampSpring} from './book-motion.js';
import {initializeCloud,cloudUser,loadCloudWallet} from '../cloud.js?v=40';
import {monthlyTimeline,money} from '../engine.js?v=28';
const $=s=>document.querySelector(s);let reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
const scene=new T.Scene();scene.background=new T.Color('#28322d');scene.fog=new T.Fog('#28322d',8,19);
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch{$('#loading small').textContent='Il 3D non è disponibile in questo browser. Apri l’ufficio classico dal logo.';throw new Error('WebGL unavailable');}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;$('#stage').append(renderer.domElement);
const camera=new T.PerspectiveCamera(38,innerWidth/innerHeight,.04,35);
const composer=new EffectComposer(renderer),beauty=new RenderPass(scene,camera),ao=new SSAOPass(scene,camera,innerWidth,innerHeight,16),output=new OutputPass();ao.kernelRadius=.10;ao.minDistance=.001;ao.maxDistance=.12;ao.enabled=innerWidth>=700;beauty.enabled=true;composer.addPass(beauty);composer.addPass(ao);composer.addPass(output);
const environment=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),env=pmrem.fromScene(environment,.02);scene.environment=env.texture;scene.environmentIntensity=.3;environment.dispose();pmrem.dispose();
const loader=new T.TextureLoader();
const [woodMap,woodNormal,woodRough]=await Promise.all(['Diffuse','nor_gl','Rough'].map(k=>loader.loadAsync(`assets/materials/wood-${k}.jpg`).catch(()=>null)));
for(const tex of [woodMap,woodNormal,woodRough])if(tex){tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.repeat.set(2,1.3);tex.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());}if(woodMap)woodMap.colorSpace=T.SRGBColorSpace;
const materialTextures=await Promise.all(['brown_leather','painted_plaster_wall'].flatMap(asset=>['Diffuse','nor_gl','Rough'].map(k=>loader.loadAsync(`assets/materials/${asset}-${k}.jpg`).catch(()=>null))));
for(let i=0;i<materialTextures.length;i++){const texture=materialTextures[i];if(!texture)continue;texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.repeat.set(i<3?1:3,i<3?1:2);texture.anisotropy=8;if(i%3===0)texture.colorSpace=T.SRGBColorSpace;}
const mat=(color,roughness=.7,metalness=0)=>new T.MeshStandardMaterial({color,roughness,metalness});
const wood=new T.MeshStandardMaterial({color:'#bca185',map:woodMap,normalMap:woodNormal,normalScale:new T.Vector2(.35,.35),roughnessMap:woodRough,roughness:.76});const darkWood=mat('#302c23',.65),brass=mat('#aa8650',.3,.8),ink=mat('#192a26',.8),ivory=mat('#e5dfc9',.94);
function mesh(geo,material,parent=scene){const m=new T.Mesh(geo,material);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function box(w,h,d,x,y,z,material,parent=scene){const m=mesh(new RoundedBoxGeometry(w,h,d,2,Math.min(.012,w*.12,h*.12,d*.12)),material,parent);m.position.set(x,y,z);return m;}
function cylinder(r1,r2,h,x,y,z,material,parent=scene){const m=mesh(new T.CylinderGeometry(r1,r2,h,40),material,parent);m.position.set(x,y,z);return m;}
function rod(a,b,r,material,parent=scene){const va=new T.Vector3(...a),vb=new T.Vector3(...b),m=mesh(new T.CylinderGeometry(r,r,va.distanceTo(vb),16),material,parent);m.position.copy(va).add(vb).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),vb.sub(va).normalize());return m;}
function canvasTexture(draw,w=1024,h=1400){const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.anisotropy=8;return t;}
const noise=canvasTexture((c,w,h)=>{c.fillStyle='#827765';c.fillRect(0,0,w,h);let seed=52;for(let i=0;i<48000;i++){seed=(seed*16807)%2147483647;const x=seed%w;seed=(seed*16807)%2147483647;const y=seed%h;c.fillStyle=i%2?'#aa9d8970':'#29231670';c.fillRect(x,y,1.6,1.2);}},512,512);noise.wrapS=noise.wrapT=T.RepeatWrapping;noise.repeat.set(4,4);
const leather=new T.MeshStandardMaterial({color:'#7f6146',map:materialTextures[0],normalMap:materialTextures[1],normalScale:new T.Vector2(.45,.45),roughnessMap:materialTextures[2],roughness:.86});
// Architecture, all solid geometry: the camera and objects inhabit the same room.
const floorWood=wood.clone();floorWood.map=woodMap?.clone();if(floorWood.map){floorWood.map.repeat.set(8,8);floorWood.map.needsUpdate=true;}floorWood.roughness=.97;box(10,.12,10,0,-.07,0,floorWood);box(10,4.6,.12,0,2.25,-2.6,new T.MeshStandardMaterial({color:'#536151',map:materialTextures[3],normalMap:materialTextures[4],normalScale:new T.Vector2(.35,.35),roughnessMap:materialTextures[5],roughness:.98}));box(.12,4.6,8,-4,2.25,.7,new T.MeshStandardMaterial({color:'#67715f',map:materialTextures[3],normalMap:materialTextures[4],normalScale:new T.Vector2(.35,.35),roughnessMap:materialTextures[5],roughness:.98}));
box(8,.16,.06,0,.14,-2.5,darkWood);box(8,.035,.03,0,1.1,-2.51,brass);
// Tall window and real slats cast bands of afternoon light.
box(.08,4,5,3.4,2,-.3,mat('#b4ae97'));const windowMat=new T.MeshBasicMaterial({color:'#e9e4d4'});box(.09,2.45,2.9,3.33,2.3,-.9,windowMat);
for(const z of [-2.42,.62])box(.18,2.7,.08,3.22,2.3,z,darkWood);for(const y of [1,3.58])box(.18,.09,3.15,3.22,y,-.9,darkWood);
for(let i=0;i<16;i++){const slat=box(.27,.026,3,3.14,1.13+i*.153,-.9,mat('#72634d'));slat.rotation.z=.28;}
const sunlight=new T.DirectionalLight('#ffe3b0',3.2);sunlight.position.set(3.05,3.35,-.9);sunlight.target.position.set(-1,.4,.9);scene.add(sunlight,sunlight.target);sunlight.castShadow=true;sunlight.shadow.mapSize.set(2048,2048);Object.assign(sunlight.shadow.camera,{left:-4,right:4,top:4,bottom:-4,near:.1,far:12});sunlight.shadow.bias=-.00012;sunlight.shadow.normalBias=.012;sunlight.shadow.radius=3;
scene.add(new T.HemisphereLight('#c8d6dc','#5e422d',.85));const fill=new T.DirectionalLight('#c5d8e3',.45);fill.position.set(-3,3,4);scene.add(fill);
// Worn woven rug and a upholstered visitor chair give the desk a human scale.
const rugTex=canvasTexture((c,w,h)=>{c.fillStyle='#666552';c.fillRect(0,0,w,h);c.strokeStyle='#a18e67';c.lineWidth=22;c.strokeRect(38,38,w-76,h-76);c.strokeStyle='#333f35';c.lineWidth=3;for(let y=0;y<h;y+=6){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}c.strokeStyle='#baa88644';for(let x=0;x<w;x+=4){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}},1024,1024);
box(3.6,.008,2.9,.05,.006,.2,new T.MeshStandardMaterial({map:rugTex,roughness:1,bumpMap:noise,bumpScale:.002}));
const chair=new T.Group();chair.position.set(.25,0,-1.16);chair.rotation.y=.09;scene.add(chair);box(.53,.09,.48,0,.47,0,leather,chair);const back=box(.53,.53,.08,0,.77,-.22,leather,chair);back.rotation.x=-.1;for(const x of [-.21,.21])for(const z of [-.19,.19])rod([x,.02,z],[x,.46,z],.018,darkWood,chair);
// Bookcase and quiet objects in the room.
box(2.1,.07,.36,-1.65,1.55,-2.32,wood);box(2.1,.07,.36,-1.65,2.25,-2.32,wood);
for(let i=0;i<5;i++){box(.34,.035,.23,-2.32,2.3+i*.039,-2.30,mat(['#9c8c68','#314238','#746b54'][i%3]));}
cylinder(.12,.07,.29,-1.03,2.43,-2.29,mat('#97866a',.9));
for(let i=0;i<18;i++){const h=.25+Math.sin(i*13)**2*.2;const b=box(.055+(i%3)*.012,h,.19,-2.58+i*.101,1.59+h/2,-2.30,mat(['#615444','#263c34','#9e9171','#4a3329'][i%4]));if(i===16)b.rotation.z=.18;}
// Framed print.
box(1.05,.85,.055,.1,2.26,-2.50,darkWood);const print=canvasTexture((c,w,h)=>{c.fillStyle='#d7ccb2';c.fillRect(0,0,w,h);c.strokeStyle='#787861';c.lineWidth=5;for(let i=0;i<9;i++){c.beginPath();c.arc(w/2,h*.7,70+i*33,Math.PI,0);c.stroke();}c.font='23px Georgia';c.fillStyle='#354139';c.fillText('ORDINE / SPAZIO / TEMPO',70,h-65);},800,600);const art=mesh(new T.PlaneGeometry(.94,.73),new T.MeshStandardMaterial({map:print,roughness:1}));art.position.set(.1,2.26,-2.466);
// Desk: full thickness, rails, legs, drawers.
box(2.8,.095,1.48,0,.77,0,wood);box(2.66,.15,1.31,0,.67,0,darkWood);for(const x of [-1.23,1.23])for(const z of [-.59,.59])box(.075,.64,.075,x,.32,z,darkWood);
box(.66,.12,.02,-.72,.65,.665,wood);rod([-.88,.65,.687],[-.59,.65,.687],.012,brass);
box(1.42,.007,.84,.02,.823,.08,new T.MeshStandardMaterial({color:'#263931',bumpMap:noise,bumpScale:.001,roughness:.96}));
// Banker’s lamp, glowing shade and pool of light.
const oldLampStart=scene.children.length;
cylinder(.14,.18,.035,-.99,.841,-.42,brass);rod([-.99,.86,-.42],[-.99,1.22,-.42],.017,brass);rod([-.99,1.22,-.42],[-.99,1.25,-.25],.017,brass);
const shade=mesh(new T.SphereGeometry(.22,40,24,0,Math.PI*2,0,Math.PI*.53),new T.MeshPhysicalMaterial({color:'#244a35',roughness:.22,metalness:.12,clearcoat:1,side:T.DoubleSide}));shade.scale.set(1,.52,.68);shade.position.set(-.99,1.26,-.23);const lamp=new T.PointLight('#ffc17c',.55,2,2);lamp.position.set(-.99,1.23,-.23);scene.add(lamp);
const oldLamp=scene.children.slice(oldLampStart).filter(o=>!o.isLight);
// Laptop remains part of the set, no fake click functionality.
const laptop=new T.Group();laptop.position.set(.55,.832,-.42);laptop.rotation.y=-.18;scene.add(laptop);box(.54,.019,.34,0,0,0,mat('#585c57',.35,.7),laptop);const lid=new T.Group();lid.position.set(0,.013,-.16);lid.rotation.x=-.16;laptop.add(lid);box(.54,.35,.017,0,.175,0,mat('#3f4541',.4,.7),lid);const screen=mesh(new T.PlaneGeometry(.492,.305),new T.MeshStandardMaterial({color:'#12362e',emissive:'#15392b',emissiveIntensity:.6,roughness:.2}),lid);screen.position.set(0,.176,.01);for(let r=0;r<4;r++)for(let k=0;k<11;k++)box(.031,.003,.025,-.204+k*.039,.012,-.1+r*.038,mat('#252b27'),laptop);
// Coffee cup with modeled lip, coffee surface and slow steam.
cylinder(.068,.056,.12,.96,.88,.34,mat('#d4ccb5',.28));const lip=mesh(new T.TorusGeometry(.067,.004,12,48),ivory);lip.rotation.x=Math.PI/2;lip.position.set(.96,.944,.34);cylinder(.063,.063,.003,.96,.934,.34,mat('#29190e',.16));const handle=mesh(new T.TorusGeometry(.037,.009,12,32),ivory);handle.position.set(1.029,.897,.34);cylinder(.10,.10,.009,.96,.825,.34,ivory);
const steamGeo=new T.BufferGeometry(),steamPos=new Float32Array(36*3);steamGeo.setAttribute('position',new T.BufferAttribute(steamPos,3));const steam= new T.Points(steamGeo,new T.PointsMaterial({color:'#e3dfd0',size:.016,transparent:true,opacity:.16,depthWrite:false}));scene.add(steam);
// Loose letter with a slightly lifted edge; a pen and a brass paperclip.
const letterTex=canvasTexture((c,w,h)=>{c.fillStyle='#ddd5c1';c.fillRect(0,0,w,h);c.fillStyle='#5b6255';c.font='28px Georgia';c.fillText('Rientro / Corrispondenza',65,100);c.fillStyle='#a5a08d';for(let i=0;i<16;i++)c.fillRect(65,210+i*36,500+(i%3)*80,3);});const letterGeo=new T.PlaneGeometry(.29,.4,10,20);letterGeo.rotateX(-Math.PI/2);const letter=mesh(letterGeo,new T.MeshStandardMaterial({map:letterTex,side:T.DoubleSide,roughness:1}));letter.position.set(-.91,.824,.24);letter.rotation.y=.19;const letterBase=letterGeo.attributes.position.array.slice();rod([.7,.835,.05],[.77,.835,.45],.008,brass);rod([.764,.835,.412],[.78,.835,.50],.007,ink);
// Detailed CC0 furniture supplements the articulated objects authored in this scene.
const gltfLoader=new GLTFLoader();
async function furniture(asset,height,position,yaw,onLoaded){try{const loaded=await gltfLoader.loadAsync(`assets/models/${asset}/model.gltf`);const model=loaded.scene;const bounds=new T.Box3().setFromObject(model),size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3());const holder=new T.Group();holder.add(model);model.position.set(-center.x,-bounds.min.y,-center.z);holder.scale.setScalar(height/size.y);holder.position.set(...position);holder.rotation.y=yaw;holder.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;for(const m of [o.material].flat()){m.envMapIntensity=.6;if(m.map)m.map.anisotropy=8;}}});scene.add(holder);onLoaded();return holder;}catch{return null;}}
await Promise.all([furniture('desk_lamp_arm_01',.64,[-1.02,.82,-.37],.8,()=>oldLamp.forEach(o=>o.visible=false)),furniture('mid_century_lounge_chair',.98,[.24,0,-1.19],0,()=>chair.visible=false)]);
lamp.position.set(-.84,1.24,-.18);lamp.intensity=.8;
// The agenda is bound to a permanent world-space location on the desk.
const book=new T.Group();book.position.set(.02,.841,.27);book.rotation.y=-.08;scene.add(book);const W=.46,D=.65;
box(.49,.019,.69,0,0,0,leather,book);const paperBlock=box(.455,.029,.65,0,.023,0,ivory,book);
for(let i=0;i<12;i++)box(.455,.00045,.651,0,.010+i*.0023,0,mat(i%3?'#c6bea8':'#eee4cc'),book);
const hinge=new T.Group();hinge.position.set(-.24,.052,0);book.add(hinge);box(.49,.014,.69,.245,0,0,leather,hinge);
const coverTex=canvasTexture((c,w,h)=>{c.clearRect(0,0,w,h);c.strokeStyle='#ab8b4d';c.lineWidth=2;c.strokeRect(48,55,w-96,h-110);c.strokeRect(58,65,w-116,h-130);c.fillStyle='#c4a35e';c.font='27px Georgia';c.fillText('R  I  E  N  T  R  O',106,180);c.font='italic 104px Georgia';c.fillText('Appunti',106,665);c.fillText('di vita.',106,785);c.font='22px Georgia';c.fillText('PERSONALE / 2026',106,1190);});const coverLabel=mesh(new T.PlaneGeometry(.46,.655),new T.MeshStandardMaterial({map:coverTex,transparent:true,metalness:.65,roughness:.4,depthWrite:false}),hinge);coverLabel.rotation.x=-Math.PI/2;coverLabel.position.set(.245,.0075,0);coverLabel.castShadow=false;
// Fine stitching around the cover, physically following its hinge.
for(let i=0;i<45;i++){for(const z of [-.323,.323])box(.003,.001,.001,.03+i*.0095,.008,z,brass,hinge);}for(let i=0;i<55;i++)for(const x of [.018,.47])box(.001,.001,.003,x,.008,-.31+i*.0115,brass,hinge);
const ribbon=box(.012,.001,.16,.15,.002,.385,mat('#8b452d'),book);ribbon.rotation.y=.04;
let dataUserId=null,wallet=null,owner='La tua agenda',page=0,notes='',noteKey='rientro-studio-demo-note',isOpen=false,focused=false,turning=false,openValue=0,openVelocity=0,openTarget=0,turnValue=0,turnVelocity=0,turnTarget=0,drag=null,turnDirection=1,closeAfterTurn=false,hidden=false,last=0,elapsed=0;
function paperTexture(which,mirror=false){return canvasTexture((c,w,h)=>{if(mirror){c.translate(w,0);c.scale(-1,1);}c.fillStyle='#e9e1cb';c.fillRect(0,0,w,h);c.fillStyle='#766f5c';c.font='20px Arial';c.fillText('R I E N T R O   /   P E R S O N A L E',78,94);c.strokeStyle='#a99d80';c.lineWidth=1;c.beginPath();c.moveTo(78,126);c.lineTo(w-78,126);c.stroke();c.fillStyle='#303b32';
 const title=(s,y=230)=>{c.font='62px Georgia';c.fillText(s,78,y);};
 if(which===0){title('Le cose');title('che contano.',306);c.font='italic 70px Georgia';c.fillText(owner.slice(0,24),78,565);c.font='25px Georgia';c.fillText('Un po’ di ordine.',78,1080);c.fillText('Un po’ di spazio per te.',78,1120);}
 if(which===1){title('Da ricordare.');c.font='23px Arial';c.fillText(new Date().toLocaleDateString('it-IT',{month:'long',year:'numeric'}).toUpperCase(),78,295);const events=wallet?monthlyTimeline(wallet).slice(0,8):[];if(!events.length){c.font='italic 30px Georgia';c.fillText(wallet?'Nessuna scadenza questo mese.':'Le tue scadenze appariranno qui.',78,425);}for(let i=0;i<events.length;i++){const e=events[i],y=410+i*102;c.fillStyle='#8e6c42';c.font='42px Georgia';c.fillText(String(e.day).padStart(2,'0'),78,y);c.fillStyle='#303b32';c.font='27px Georgia';c.fillText(e.label.slice(0,30),165,y-4);c.font='21px Arial';c.fillText(money(e.amount)+'  /  '+(e.status==='done'?'Registrato':e.status==='overdue'?'Da verificare':'In programma'),165,y+29);c.fillStyle='#b8ac91';c.fillRect(78,y+53,w-156,1);}}
 if(which===2){title('Meno rumore.');title('Più direzione.',306);c.font='italic 34px Georgia';c.fillText('Una cosa alla volta.',78,610);c.fillText('Ma quella che conta.',78,668);c.strokeStyle='#8e6c42';c.strokeRect(78,800,280,130);c.font='22px Arial';c.fillText('IL TEMPO È TUO',98,871);}
 if(which===3){title('I tuoi appunti.');c.font='20px Arial';c.fillText('SALVATI SU QUESTO DISPOSITIVO',78,292);c.strokeStyle='#bcb09a';for(let y=385;y<1250;y+=58){c.beginPath();c.moveTo(78,y);c.lineTo(w-78,y);c.stroke();}c.fillStyle='#274255';c.font='italic 32px Georgia';const lines=[];for(const paragraph of (notes||'').split('\n')){let line='';for(const word of paragraph.split(' ')){if(c.measureText(line+word).width>w-170){lines.push(line);line='';}line+=word+' ';}lines.push(line);}lines.slice(0,15).forEach((l,i)=>c.fillText(l,84,373+i*58));}
 c.fillStyle='#766f5c';c.font='21px Georgia';c.fillText(String(which+1).padStart(2,'0'),w-110,h-65);
 });}
function makeSheet(progress,front,back){const geo=new T.PlaneGeometry(W,D,48,20);geo.rotateX(-Math.PI/2);const group=new T.Group();group.position.set(-.23,.041,0);book.add(group);const fm=new T.MeshStandardMaterial({map:front,side:T.FrontSide,roughness:.98}),bm=new T.MeshStandardMaterial({map:back,side:T.BackSide,roughness:.98});mesh(geo,fm,group);mesh(geo,bm,group);const sheet={group,geo,fm,bm};shape(sheet,progress);return sheet;}
function shape(sheet,p){const a=sheet.geo.attributes.position;for(let i=0;i<a.count;i++){const ix=i%49,iz=Math.floor(i/49),v=iz/20,pt=pagePoint(ix/48,v,p,W,D);a.setXYZ(i,pt.x,pt.y,pt.z);}a.needsUpdate=true;sheet.geo.computeVertexNormals();sheet.geo.computeBoundingSphere();}
// Geometry row orientation has upward normals after mapping z from rear to front.
const right=makeSheet(0,paperTexture(1),paperTexture(1,true));const left=makeSheet(1,paperTexture(0),paperTexture(0,true));left.group.position.y=.064;left.group.visible=false;
const leaf=makeSheet(0,paperTexture(1),paperTexture(2,true));leaf.group.position.y=.042;leaf.group.visible=false;
function setMap(material,texture){material.map?.dispose();material.map=texture;material.needsUpdate=true;}
function layLeft(which){if(which===0){hinge.add(left.group);left.group.position.set(.01,-.012,0);shape(left,0);}else{book.add(left.group);left.group.position.set(-.23,.064,0);shape(left,1);}}
layLeft(0);
function refreshPages(){layLeft(page);setMap(right.fm,paperTexture(page===0?1:3));setMap(right.bm,paperTexture(page===0?1:3,true));setMap(left.bm,paperTexture(page===0?0:2,true));setMap(left.fm,paperTexture(page===0?0:2));$('#accessible-page').textContent=page===0?`${owner}. ${wallet?monthlyTimeline(wallet).map(e=>`${e.day}: ${e.label}, ${money(e.amount)}`).join('. '):'Nessun dato personale caricato.'}`:`Appunti: ${notes}`;}
let cameraMove=null;const look=new T.Vector3(),pointer=new T.Vector2(),ray=new T.Raycaster(),projection=new T.Vector3();
function homePose(){return innerWidth<700?{pos:[-2.4,2.65,3.7],look:[.15,1.05,-.2]}:{pos:[-2.1,2.25,3.1],look:[.12,1.14,-.25]};}
function bookPose(){return innerWidth<700?{pos:[-.22,3.9,1.85],look:[-.18,.86,.25]}:{pos:[.03,1.92,1.38],look:[-.17,.86,.26]};}
let basePos=new T.Vector3(...homePose().pos);look.set(...homePose().look);camera.position.copy(basePos);camera.lookAt(look);
function moveCamera(pose,duration=1600){cameraMove={from:basePos.clone(),to:new T.Vector3(...pose.pos),fromLook:look.clone(),toLook:new T.Vector3(...pose.look),start:performance.now(),duration:reduced?1:duration};}
function controls(){$('#stage').dataset.bookState=isOpen?'open':'closed';$('#stage').dataset.page=String(page+1);$('#stage').dataset.turning=String(turning);for(const id of ['prev','next','close','wide'])$('#'+id).hidden=!isOpen;$('#close').disabled=turning;$('#prev').disabled=page===0||turning;$('#next').disabled=page===1||turning;$('#write').hidden=!isOpen||page!==1||turning;$('#agenda-target').hidden=isOpen;document.body.classList.toggle('focused',focused);$('#intro').setAttribute('aria-hidden',String(focused));}
function openBook(){if(isOpen)return;isOpen=true;focused=true;openTarget=Math.PI-.004;left.group.visible=true;moveCamera(bookPose());$('#hint').textContent='Attrappa il bordo destro del foglio e trascinalo, oppure usa Sfoglia.';controls();}
function closeBook(){if(turning)return;if(page===1){closeAfterTurn=true;startTurn(-1);return;}isOpen=false;openTarget=0;$('#note-input').blur();$('#hint').textContent='La copertina torna sulla scrivania.';controls();setTimeout(()=>{if(!isOpen){focused=false;moveCamera(homePose(),1900);controls();$('#hint').textContent='Tocca l’agenda per riaprirla.';}},reduced?0:1000);}
function startTurn(direction,manual=false){if(!isOpen||turning||openValue<2.7||(direction===1&&page===1)||(direction===-1&&page===0))return false;turning=true;turnDirection=direction;turnValue=direction===1?0:1;turnVelocity=0;turnTarget=manual?turnValue:(direction===1?1:0);setMap(leaf.fm,paperTexture(1));setMap(leaf.bm,paperTexture(2,true));leaf.group.visible=true;if(direction===1){setMap(right.fm,paperTexture(3));}else{layLeft(0);setMap(left.bm,paperTexture(0,true));}controls();return true;}
$('#agenda-target').onclick=openBook;$('#next').onclick=()=>startTurn(1);$('#prev').onclick=()=>startTurn(-1);$('#close').onclick=closeBook;$('#wide').onclick=()=>{focused=!focused;moveCamera(focused?bookPose():homePose(),1800);controls();$('#wide').textContent=focused?'Guarda l’ufficio':'Avvicinati';};$('#motion').setAttribute('aria-pressed',String(reduced));$('#motion').onclick=()=>{reduced=!reduced;$('#motion').setAttribute('aria-pressed',String(reduced));};
$('#write').onclick=()=>{$('#note-input').value=notes;$('#note-input').focus();$('#hint').textContent='Scrivi direttamente sulla pagina. Le note restano su questo dispositivo.';};$('#note-input').oninput=()=>{notes=$('#note-input').value;try{localStorage.setItem(noteKey,notes);}catch{$('#hint').textContent='Salvataggio non disponibile: copia la nota prima di uscire.';}refreshPages();};
function hit(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObject(book,true).find(h=>{let object=h.object;while(object){if(!object.visible)return false;object=object.parent;}return true;});}
renderer.domElement.addEventListener('pointerdown',e=>{const h=hit(e);if(!h)return;if(!isOpen){openBook();return;}const local=book.worldToLocal(h.point.clone());const dir=local.x<-.23?-1:1;if(startTurn(dir,true)){drag={id:e.pointerId,x:e.clientX,start:turnValue};renderer.domElement.setPointerCapture(e.pointerId);}});
renderer.domElement.addEventListener('pointermove',e=>{if(drag){turnTarget=T.MathUtils.clamp(drag.start+(drag.x-e.clientX)/(innerWidth*.36),0,1);}else renderer.domElement.style.cursor=hit(e)?'pointer':'default';});
function release(e){if(!drag||drag.id!==e.pointerId)return;const initial=drag.start;drag=null;turnTarget=e.type==='pointercancel'?initial:(turnTarget>.5?1:0);}
renderer.domElement.addEventListener('pointerup',release);renderer.domElement.addEventListener('pointercancel',release);
document.addEventListener('keydown',e=>{if(e.target===$('#note-input')){if(e.key==='Escape')e.target.blur();return;}if(e.key==='Escape'&&isOpen)closeBook();if(e.key==='ArrowRight'){e.preventDefault();startTurn(1);}if(e.key==='ArrowLeft'){e.preventDefault();startTurn(-1);}});
// Living room details: a soft curtain, airborne dust, steam and moving paper corners.
const curtainGeo=new T.PlaneGeometry(1,2.7,20,35);const curtain=mesh(curtainGeo,new T.MeshStandardMaterial({color:'#c1b89e',roughness:1,side:T.DoubleSide,transparent:true,opacity:.83}));curtain.position.set(3.02,2.1,.68);curtain.rotation.y=-Math.PI/2;const curtainBase=curtainGeo.attributes.position.array.slice();
const dustGeo=new T.BufferGeometry(),dustArray=new Float32Array(80*3);for(let i=0;i<80;i++){dustArray[i*3]=(Math.random()-.5)*3;dustArray[i*3+1]=.9+Math.random()*1.8;dustArray[i*3+2]=(Math.random()-.5)*2;}dustGeo.setAttribute('position',new T.BufferAttribute(dustArray,3));const dust=new T.Points(dustGeo,new T.PointsMaterial({color:'#e9d4a9',size:.005,transparent:true,opacity:.35,depthWrite:false}));scene.add(dust);
let raf=0;function frame(now){if(hidden)return;raf=requestAnimationFrame(frame);const dt=Math.min(.04,(now-(last||now))/1000);last=now;elapsed+=reduced?0:dt;
 if(cameraMove){const p=Math.min(1,(now-cameraMove.start)/cameraMove.duration),e=smoothCamera(p);basePos.lerpVectors(cameraMove.from,cameraMove.to,e);look.lerpVectors(cameraMove.fromLook,cameraMove.toLook,e);if(p===1)cameraMove=null;}
 camera.position.copy(basePos);if(!reduced){camera.position.x+=Math.sin(elapsed*.43)*.0025;camera.position.y+=Math.sin(elapsed*.61)*.0014;}camera.lookAt(look);
 if(reduced){openValue=openTarget;openVelocity=0;}else{const s=dampSpring(openValue,openVelocity,openTarget,dt,44,14);openValue=s.value;openVelocity=s.velocity;}hinge.rotation.z=openValue;left.group.visible=openValue>.15;
 if(turning){if(reduced&&!drag){turnValue=turnTarget;turnVelocity=0;}else{const s=dampSpring(turnValue,turnVelocity,turnTarget,dt,drag?100:48,drag?21:13);turnValue=T.MathUtils.clamp(s.value,0,1);turnVelocity=s.velocity;}leaf.group.position.y=.043+.021*turnValue;shape(leaf,turnValue);if(!drag&&Math.abs(turnValue-turnTarget)<.001&&Math.abs(turnVelocity)<.02){page=turnTarget===1?1:0;turning=false;leaf.group.visible=false;refreshPages();controls();if(closeAfterTurn){closeAfterTurn=false;closeBook();}}}
 const ca=curtainGeo.attributes.position;for(let i=0;i<ca.count;i++){const x=curtainBase[i*3],y=curtainBase[i*3+1];ca.setZ(i,Math.sin(x*30)*.035+Math.sin(elapsed*.7+x*3)*.018*(1.4-y));}ca.needsUpdate=true;curtainGeo.computeVertexNormals();
 const la=letterGeo.attributes.position;for(let i=0;i<la.count;i++)la.setY(i,Math.max(0,letterBase[i*3+2])**2*(.35+Math.sin(elapsed*1.1)*.05));la.needsUpdate=true;letterGeo.computeVertexNormals();
 for(let i=0;i<36;i++){const p=(elapsed*.16+i/36)%1;steamPos[i*3]=.96+Math.sin(p*9+elapsed*.4)*.019;steamPos[i*3+1]=.95+p*.22;steamPos[i*3+2]=.34+Math.cos(p*8)*.015;}steamGeo.attributes.position.needsUpdate=true;dust.rotation.y=Math.sin(elapsed*.06)*.06;
 projection.set(.10,.07,.04).applyMatrix4(book.matrixWorld).project(camera);$('#agenda-target').style.left=((projection.x+1)/2*innerWidth)+'px';$('#agenda-target').style.top=((1-projection.y)/2*innerHeight)+'px';
 composer.render();
}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);ao.enabled=innerWidth>=700;beauty.enabled=true;moveCamera(focused?bookPose():homePose(),600);}addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{hidden=document.hidden;if(hidden)cancelAnimationFrame(raf);else{last=0;raf=requestAnimationFrame(frame);}});
controls();raf=requestAnimationFrame(frame);$('#agenda-target').disabled=false;$('#loading').style.opacity='0';setTimeout(()=>$('#loading').hidden=true,650);$('#data-label').textContent='Studio 3D · anteprima interattiva';$('#hint').textContent='Tocca l’agenda sulla scrivania. Trascina i fogli per sfogliarli.';
try{const auth=await initializeCloud();if(auth.user){const loaded=await loadCloudWallet();if(!cloudUser()||(cloudUser().id||cloudUser().email)!==(auth.user.id||auth.user.email))throw new Error('Session changed');dataUserId=auth.user.id||auth.user.email;wallet=loaded;owner=wallet?.name||'La tua agenda';noteKey=`rientro-studio-notes:${auth.user.id||auth.user.email}`;$('#data-label').textContent='Agenda collegata al tuo account';}else $('#data-label').textContent='Anteprima · nessun dato personale caricato';try{notes=localStorage.getItem(noteKey)||'';}catch{}refreshPages();}catch{$('#data-label').textContent='Anteprima · dati cloud non disponibili';}
window.addEventListener('rientro-cloud-status',()=>{if(!cloudUser()||(dataUserId&&dataUserId!==(cloudUser().id||cloudUser().email))){dataUserId=null;wallet=null;owner='La tua agenda';notes='';$('#note-input').value='';$('#note-input').blur();noteKey='rientro-studio-demo-note';refreshPages();$('#data-label').textContent='Anteprima · nessun dato personale caricato';}});
addEventListener('pagehide',()=>{cancelAnimationFrame(raf);scene.traverse(o=>{o.geometry?.dispose();for(const m of [o.material].flat()){if(!m)continue;for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}});env.dispose();ao.dispose();output.dispose();composer.dispose();renderer.dispose();},{once:true});
